#! python3

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')
print("Welcome to Treasure Island.")
print("Your mission is to find the treasure.") 

firstMove = input("You are at an empass. Do you want to go left or right? Type left or right ")

if firstMove.lower() == "left":
    print("Great Choice")
    secondMove = input("The bridge is broken. Do you swim or wait? type swim or wait ")
    if secondMove.lower() == "wait":
        print("Waiting is a virtue.")
        thirdMove = input("You reached the last door! What color is it? ")
        if thirdMove.lower() == "yellow":
            print("You Win!")
        elif thirdMove.lower() == "red":
            print("Burned by fire. Game Over.")
        elif thirdMove.lower() == "blue":
            print("Eaten by beasts. Game Over.")
        elif thirdMove.lower() == "brown":
            print("Building falls on you. Game Over.")
        elif thirdMove.lower() == "black":
            print("Sucked into empty space. Game Over.")
        elif thirdMove.lower() == "green":
            print("Eaten by carnivorous plants. Game Over.")
        elif thirdMove.lower() == "purple":
            print("Inhaled poison mist. Game Over.")
        elif thirdMove.lower() == "pink":
            print("Mesmorized by mysterious orb. Game Over.")
        else:
            print("Game Over.")
    else:
        print("Attacked by trout. Game Over.")
else:
    print("Fall into a hole. Game Over.")
